version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: gametime-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: games
      # These are for the DB itself, not for the backend
      # USUARIO: user
      # SENHA: password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: .
    container_name: gametime-backend
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    # --- CORREÇÃO AQUI ---
    environment:
      MYSQL_HOST: db #  <-- Tells Spring to connect to the 'db' service
      USUARIO: root   #  <-- Use the root user defined in the db service
      SENHA: root     #  <-- Use the root password defined in the db service

volumes:
  db_data: